#ifndef CAIRO_FEATURES_H
#define CAIRO_FEATURES_H
#define CL_CAIRO2_USING_XLIB 1

#define CAIRO_HAS_XLIB_XRENDER_SURFACE 1
#define CAIRO_HAS_XLIB_SURFACE 1
#define CAIRO_HAS_FT_FONT 1
#define CAIRO_HAS_FC_FONT 1

#endif
