;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 2.0.4
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(in-package :cl-cairo2)



(cl:defconstant CAIRO_HAS_XCB_SURFACE 1)

(cl:defconstant CAIRO_HAS_FT_FONT 1)

(cl:defconstant CAIRO_HAS_FC_FONT 1)

(cffi:defcfun ("cairo_xcb_surface_create" cairo_xcb_surface_create) :pointer
  (connection :pointer)
  (drawable :unsigned-long)
  (visual :pointer)
  (width :int)
  (height :int))

(cffi:defcfun ("cairo_xcb_surface_create_for_bitmap" cairo_xcb_surface_create_for_bitmap) :pointer
  (connection :pointer)
  (screen :pointer)
  (bitmap :pointer)
  (width :int)
  (height :int))

(cffi:defcfun ("cairo_xcb_surface_create_with_xrender_format" cairo_xcb_surface_create_with_xrender_format) :pointer
  (connection :pointer)
  (screen :pointer)
  (drawable :unsigned-long)
  (format :pointer)
  (width :int)
  (height :int))

(cffi:defcfun ("cairo_xcb_surface_set_size" cairo_xcb_surface_set_size) :void
  (surface :pointer)
  (width :int)
  (height :int))

(cffi:defcfun ("cairo_xcb_surface_set_drawable" cairo_xcb_surface_set_drawable) :void
  (surface :pointer)
  (drawable :unsigned-long)
  (width :int)
  (height :int))

(cffi:defcfun ("cairo_xcb_device_get_connection" cairo_xcb_device_get_connection) :pointer
  (device :pointer))

(cffi:defcfun ("cairo_xcb_device_debug_cap_xshm_version" cairo_xcb_device_debug_cap_xshm_version) :void
  (device :pointer)
  (major_version :int)
  (minor_version :int))

(cffi:defcfun ("cairo_xcb_device_debug_cap_xrender_version" cairo_xcb_device_debug_cap_xrender_version) :void
  (device :pointer)
  (major_version :int)
  (minor_version :int))

(cffi:defcfun ("cairo_xcb_device_debug_set_precision" cairo_xcb_device_debug_set_precision) :void
  (device :pointer)
  (precision :int))

(cffi:defcfun ("cairo_xcb_device_debug_get_precision" cairo_xcb_device_debug_get_precision) :int
  (device :pointer))

(cffi:defcfun ("cairo_ft_font_face_create_for_ft_face" cairo_ft_font_face_create_for_ft_face) :pointer
  (face :pointer)
  (load_flags :int))

(cffi:defcenum cairo_ft_synthesize_t
	(:CAIRO_FT_SYNTHESIZE_BOLD #.(cl:ash 1 0))
	(:CAIRO_FT_SYNTHESIZE_OBLIQUE #.(cl:ash 1 1)))

(cffi:defcfun ("cairo_ft_font_face_set_synthesize" cairo_ft_font_face_set_synthesize) :void
  (font_face :pointer)
  (synth_flags :unsigned-int))

(cffi:defcfun ("cairo_ft_font_face_unset_synthesize" cairo_ft_font_face_unset_synthesize) :void
  (font_face :pointer)
  (synth_flags :unsigned-int))

(cffi:defcfun ("cairo_ft_font_face_get_synthesize" cairo_ft_font_face_get_synthesize) :unsigned-int
  (font_face :pointer))

(cffi:defcfun ("cairo_ft_scaled_font_lock_face" cairo_ft_scaled_font_lock_face) :pointer
  (scaled_font :pointer))

(cffi:defcfun ("cairo_ft_scaled_font_unlock_face" cairo_ft_scaled_font_unlock_face) :void
  (scaled_font :pointer))

(cffi:defcfun ("cairo_ft_font_face_create_for_pattern" cairo_ft_font_face_create_for_pattern) :pointer
  (pattern :pointer))

(cffi:defcfun ("cairo_ft_font_options_substitute" cairo_ft_font_options_substitute) :void
  (options :pointer)
  (pattern :pointer))


