#ifndef CAIRO_FEATURES_H
#define CAIRO_FEATURES_H
#define CL_CAIRO2_USING_CORE 1

#define CAIRO_HAS_IMAGE_SURFACE 1
#define CAIRO_HAS_PNG_FUNCTIONS 1
#define CAIRO_HAS_SVG_SURFACE 1
#define CAIRO_HAS_PDF_SURFACE 1
#define CAIRO_HAS_PS_SURFACE 1
#define CAIRO_HAS_USER_FONT 1

#endif
